name: AC_Bot_windows编译

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - bot

concurrency:
  group: ${{ github.workflow }})
  cancel-in-progress: true
jobs:
  build-ubuntu:
    name: 执行编译
    runs-on: windows-latest
    env:
      BOOST_ROOT: C:\local\boost_1_82_0
    steps:
      - name: 拉取核心代码
        uses: actions/checkout@v4
        with:
          repository: 'liyunfan1223/azerothcore-wotlk'
          ref: 'Playerbot'

      - name: 拉取当前项目
        uses: actions/checkout@v4
        with:
          ref: 'build'
          path: 'build'

      - name: 拉取Eluna代码
        uses: actions/checkout@v4
        with:
          repository: 'azerothcore/mod-eluna'  
          ref: 'master'
          path: 'modules/mod-eluna'

      - name: 拉取playerbots代码
        uses: actions/checkout@v4
        with:
          repository: 'liyunfan1223/mod-playerbots'  
          ref: 'master'
          path: 'modules/mod-playerbots'

      - name: 下载并替换MotdMgr.cpp
        run: |
          curl -L -o MotdMgr.cpp https://raw.githubusercontent.com/aopkcn/acore-build/build/MotdMgr.cpp
          Move-Item -Path MotdMgr.cpp -Destination src/server/game/Motd/MotdMgr.cpp -Force

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.13
      - name: Configure OS
        shell: bash
        env:
          CONTINUOUS_INTEGRATION: true2
        run: |
          ./acore.sh install-deps
      - name: 编译
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          # export CTYPE=RelWithDebInfo
          ./acore.sh compiler build
      - name: 打包编译文件
        run: |
            mkdir -p AzerothCoreWotlkBot-Win64\modules\mod-playerbots\data
            mkdir -p AzerothCoreWotlkBot-Win64\lua_scripts
            mkdir -p AzerothCoreWotlkBot-Win64\data

            Copy-Item -Path "C:\Program Files\OpenSSL\bin\legacy.dll" -Destination AzerothCoreWotlkBot-Win64
            Copy-Item -Path "C:\Program Files\OpenSSL\bin\libcrypto-1_1-x64.dll" -Destination AzerothCoreWotlkBot-Win64
            Copy-Item -Path "C:\Program Files\OpenSSL\bin\libssl-1_1-x64.dll" -Destination AzerothCoreWotlkBot-Win64
            Copy-Item -Path "C:\tools\mysql\current\lib\libmysql.dll" -Destination AzerothCoreWotlkBot-Win64
           
            Copy-Item -Path modules\mod-playerbots\data\sql -Destination AzerothCoreWotlkBot-Win64\modules\mod-playerbots\data\sql -Recurse -Force
            Copy-Item -Path data\sql -Destination AzerothCoreWotlkBot-Win64\data -Recurse -Force
            Copy-Item -Path env\dist\configs -Destination AzerothCoreWotlkBot-Win64 -Recurse -Force
            Copy-Item -Path env\dist\authserver.exe -Destination AzerothCoreWotlkBot-Win64
            Copy-Item -Path env\dist\worldserver.exe -Destination AzerothCoreWotlkBot-Win64
            Copy-Item -Path env\dist\dbimport.exe -Destination AzerothCoreWotlkBot-Win64
            Copy-Item -Path env\dist\map_extractor.exe -Destination AzerothCoreWotlkBot-Win64
            Copy-Item -Path env\dist\mmaps_generator.exe -Destination AzerothCoreWotlkBot-Win64
            Copy-Item -Path env\dist\vmap4_assembler.exe -Destination AzerothCoreWotlkBot-Win64
            Copy-Item -Path env\dist\vmap4_extractor.exe -Destination AzerothCoreWotlkBot-Win64

            Compress-Archive -Path AzerothCoreWotlk-Win64 -DestinationPath AC-Bot-Win.zip

      #       Move-Item -Path C:\Program Files\OpenSSL\bin\legacy.dll -Destination var\build\obj\bin\RelWithDebInfo
      #       Move-Item -Path C:\Program Files\OpenSSL\bin\libcrypto-1_1-x64.dll -Destination var\build\obj\bin\RelWithDebInfo
      #       Move-Item -Path C:\Program Files\OpenSSL\bin\libssl-1_1-x64.dll -Destination var\build\obj\bin\RelWithDebInfo
      #       Move-Item -Path C:\tools\mysql\current\lib\libmysql.dll -Destination var\build\obj\bin\RelWithDebInfo
      #       Compress-Archive -Path var\build\obj\bin\RelWithDebInfo\* -DestinationPath AC-Bot-Win.zip
      - name: 上传 Windows 编译文件
        uses: actions/upload-artifact@v4
        with:
         name: AzerothCoreWotlkBot-Win64
         path: AzerothCoreWotlkBot-Win64
